name: Publish Node.js Package

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: latest
      - run: |
          sudo apt-get install -y libreoffice-core-nogui libreoffice-calc-nogui libreoffice-l10n-de
      - run: |
          yarn
      - run: |
          yarn run all

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: latest
          registry-url: https://registry.npmjs.org/
      - run: yarn
      - run: yarn run build
      - name: yarn publish
        run: |
          git config --global user.name 'Florian Wilhelm'
          git config --global user.email 'fwilhelm.wgt+github@gmail.com'
          yarn publish --patch
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_PUBLISH}}
      - name: git push
        run: git push && git push --tags
